== What is a Large Language Model?

#align(center, text(weight: "bold", size: 1.5em)[An LLM is Fancy Autocomplete])

#v(0.5em)

#grid(
  columns: (1fr, 1fr),
  align: top,
  gutter: 1em,
  [
    - Blocks of linear algebra
      - arranged in creative ways
      - trained on every scrap of human media
      - unimaginable amounts of computation
      - learn statistical patterns, not explicit rules about the world

    - Behaviour *surprisingly* emerges at scale
      - Exhibits strengths and weaknesses very different from humans
  ],
  [
    #pause
    *LLMs are black boxes*: we have limited understanding of how they work.

    *LLMs are stochastic:* Identical runs often produce different output.

    - `Sunny skies ☀️, 30°C.`
    - `30°C with plenty of sunshine.`
    - `It's sunny and 30°C today.`

    #lblock[
      *Agent engineering* extracts useful work despite these limits.
    ]

  ],
)


#speaker-note[
  - "Fancy autocomplete" is provocative on purpose
  - Return to it when students are surprised by what models do
  - Emergent capabilities at scale were not programmed
]


// Coordinates match the native-size SVGs generated by data/make_chart.py.
// The callout ends above GLM 5.3 Flash and left of GLM 5.3.
#let cost-chart(chart, body) = block(spacing: 0pt)[
  #chart

  #pause

  #place(top + left, dx: 60pt, dy: 16pt)[
    #lblock(width: 350pt, inset: 0pt, outset: 0pt)[
      #block(width: 100%, height: 78pt, inset: 10pt)[#body]
    ]
  ]
]

#let cost-chart-sources() = [
  #cite-source(
    "https://openrouter.ai/docs/api/api-reference/datasets/get-rankings-daily",
  )[OpenRouter. _Daily token totals for top 50 models_. Usage feed. Prices and listing dates: #link("https://openrouter.ai/api/v1/models")[models catalog]. Snapshot: 30 September 2026.]
  #cite-source(
    "https://artificialanalysis.ai/",
  )[Artificial Analysis, via OpenRouter. _Artificial Analysis Intelligence Index_. Benchmark snapshot: 30 September 2026. Stored curated scores and teaching overrides: 01-intro/data/README.md.]
  #cite-source(
    "https://artificialanalysis.ai/articles/gemini-4-argon-google-top-three-labs",
  )[Artificial Analysis. _Gemini 4 Argon: Google is back as one of the top three labs in intelligence achieved_. 30 September 2026. AAII 53 (high); standard input/output pricing of US\$4/US\$20 per million tokens, before the introductory discount.]
  #cite-source(
    "https://artificialanalysis.ai/models/muse-spark-1-3",
  )[Artificial Analysis. _Muse Spark 1.3 (max)_. Read 2 October 2026. AAII 48 under Intelligence Index v4.3.2; later benchmark reading than the stored September snapshot.]
]
