== Hallucinations

#slide(config: config-common(breakable: false))[
  #grid(
    columns: (1fr, 1fr),
    column-gutter: 1.5em,
    align: top,
    [
      #text(size: 28pt, weight: "bold")[South Africa withdrew its draft AI policy.]
      #v(0.6em)
      Its reference list contained *fictitious sources* that appeared to have been generated by AI.#cite-source("https://www.reuters.com/world/africa/south-africa-withdraws-ai-policy-due-fake-ai-generated-sources-2026-04-27/")[Reuters. _South Africa withdraws draft AI policy over fictitious references_. 27 April 2026. Screenshot: Reuters republication on MyJoyOnline, 28 April 2026.]

      #v(0.6em)
      #gblock(inset: 0.6em, outset: 0pt)[
        #text(
          size: 22pt,
        )[“AI-generated citations were included without proper verification. This should not have happened.”]
        #v(0.4em)
        #text(size: 14pt, fill: luma(100))[Solly Malatsi, Minister of Communications and Digital Technologies]
      ]
    ],
    [
      #link("https://www.myjoyonline.com/south-africa-withdraws-ai-policy-due-to-fake-ai-generated-sources/")[
        #align(center, screenshot-image(
          "media/hallucination/south-africa-ai-policy-reuters.png",
          [Reuters / MyJoyOnline#cite-source("https://www.myjoyonline.com/south-africa-withdraws-ai-policy-due-to-fake-ai-generated-sources/", key: "https://www.reuters.com/world/africa/south-africa-withdraws-ai-policy-due-fake-ai-generated-sources-2026-04-27/")[Reuters, republished by MyJoyOnline. _South Africa withdraws draft AI policy over fictitious references_. 28 April 2026.]],
          height: 100%,
          alt: "MyJoyOnline screenshot of a Reuters report on South Africa withdrawing its draft AI policy after fictitious references were discovered.",
        ))
      ]
    ],
  )
]

#speaker-note[
  - Reuters reported on 27 April 2026 that South Africa withdrew its first draft national AI policy after fictitious sources were found in its reference list. The draft had been released for public comment that month.
  - Malatsi described unverified AI-generated citations as the most plausible explanation; the report does not establish which model or drafting tool was used.
  - Reuters' site blocked automated access. The screenshot shows the same Reuters report republished by MyJoyOnline on 28 April 2026: https://www.myjoyonline.com/south-africa-withdraws-ai-policy-due-to-fake-ai-generated-sources/.
  - Leadership takeaway: assign a reviewer to open cited sources and check that they support the claims before publication or approval. A plausible bibliography is not evidence of verification.
]

#let principle(num, title, body, example: none) = grid(
  columns: (auto, 1fr),
  column-gutter: 0.7em,
  row-gutter: 0.1em,
  align: (right + top, left + top),
  text(weight: "bold", size: 3em, fill: luma(140))[#num.],
  [
    *#title* \
    #body
    #if example != none [
      \
      #text(size: 0.85em, fill: luma(100))[_e.g._ #example]
    ]
  ],
)

/*
== Why can't we just use ONE agent?

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1.5em,
  row-gutter: 1em,
  align: (top + left),
  principle([1], [Context rot], [keep each window small and on-task.]),
  principle([2], [Credulity], [the agent trusts too much.]),

  principle([3], [Abstraction], [allow higher-level processes to ignore irrelevant details about low-level tasks.]),
  principle([4], [Specialization], [a focused prompt and few tools beats a kitchen sink.]),

  principle([5], [Observability], [see every step, not just the answer.]),
  principle([6], [Least privilege], [scope tools per stage to avoid security breaches.]),

  principle([7], [Testability], [understand the performance of each step and build confidence.]),
  principle([8], [Cost & latency], [route cheap models for the easy steps, or get the job done quicker.]),
)

#pause
#place(center + horizon, lblock(
  width: 100%,
  inset: (x: 0.5em, y: 0.5em),
  outset: (x: -1.5em, y: 1em),
  fill: white.transparentize(6%),
  align(center + horizon)[
    One big agent fails in ways you can't see, fix, or contain.

    #scale(70%, reflow: true, include "figures/workflows/task-agent.typ")

    Balancing engineering with *business risk* is the key role of the business leader.
  ],
))

#speaker-note[
  Motivating example: a "research assistant" you ask to research a topic and email a summary.
  As ONE agent it must search the web, read ~20 pages, draft, and send the mail - all in one context.
  Walk the same eight numbers down the failure modes:
  - Context rot: 20 raw pages crowd out the original task.
  - Credulity: one poisoned page and it follows the instructions hidden in it.
  - Abstraction / Specialization: search, write, and send are jammed into one fuzzy prompt.
  - Observability: it emails the wrong person - which step went wrong? You can't tell.
  - Least privilege: it holds web + file + send-email tools the entire time.
  - Testability: you can't test "find sources" apart from "write the summary".
  - Cost & latency: a frontier model burns tokens on trivial fetches.
  Each failure maps to one principle - and each is fixed by splitting the work, which is the next section.
]
*/
